apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: devbug
resources:
  - namespace.yml
  - postgres-secret.yml
  - postgres-pvc.yml
  - postgres-deployment.yml
  - postgres-service.yml
  - backend-deployment.yml
  - backend-service.yml
  - frontend-deployment.yml
  - frontend-service.yml
